version: "3"
volumes: 
  dynamodb_data:

services:
  dynamo:
    user: root
    image: "amazon/dynamodb-local:latest"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath" , "/home/dynamodblocal/data/" ]
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
  lambda:
    image: "node:16-alpine3.16"
    user: node
    working_dir: /lambda
    command: ["/bin/sh","start-dev.sh"]
    environment:
      NODE_ENV: development
      DYNAMO_ENDPOINT: ${DYNAMO_ENDPOINT}
      BOOKS_TABLE_NAME: ${BOOKS_TABLE_NAME}

      # Note: even though these keys are no the actual keys, access key and
      # secret key is still required. Otherwise, `aws-sdk` will attempt
      # to read credentials from Amazon and it will fail.
      AWS_ACCESS_KEY_ID: "abc"
      AWS_SECRET_ACCESS_KEY: "xyz"
      AWS_REGION: "us-east-2"
    depends_on:
      - dynamo
    volumes:
      - .:/lambda
    ports:
      - "3000:3000"